name: Caching Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up the cache
        id: cache-step
        uses: actions/cache@v4
        with:
          path: './some-cache-dir'
          key: cache-2088703

      - name: prime-cache-2088703
        run: echo "Cache hit status was ${{ steps.cache-step.outputs.cache-hit }}"
